export const tabs = [
  { id: 1, label: 'Breakfast' },
  { id: 2, label: 'Lunch' },
  { id: 3, label: 'Dinner' },
  { id: 4, label: 'Snack' },
  { id: 5, label: 'TeaTime' },
]

export const dietaryOptions = [
  { href: 'wheat-free', name: 'Wheat Free' },
  { href: 'vegetarian', name: 'Vegetarian' },
  { href: 'vegan', name: 'Vegan' },
  { href: 'tree-nut-free', name: 'Tree Nut Free' },
  { href: 'sulfite-free', name: 'Sulfite Free' },
  { href: 'sugar-conscious', name: 'Sugar Conscious' },
  { href: 'soy-free', name: 'Soy Free' },
  { href: 'shellfish-free', name: 'Shellfish Free' },
  { href: 'sesame-free', name: 'Sesame Free' },
  { href: 'red-meat-free', name: 'Red Meat Free' },
  { href: 'pork-free', name: 'Pork Free' },
  { href: 'pecatarian', name: 'Pescatarian' },
  { href: 'peanut-free', name: 'Peanut Free' },
  { href: 'paleo', name: 'Paleo' },
  { href: 'No-oil-added', name: 'No Oil Added' },
  { href: 'mustard-free', name: 'Mustard Free' },
  { href: 'mollusk-free', name: 'Mollusk Free' },
  { href: 'Mediterranean', name: 'Mediterranean' },
  { href: 'lupine-free', name: 'Lupine Free' },
  { href: 'low-sugar', name: 'Low Sugar' },
  { href: 'low-potassium', name: 'Low Potassium' },
  { href: 'kosher', name: 'Kosher' },
  { href: 'kidney-friendly', name: 'Kidney Friendly' },
  { href: 'keto-friendly', name: 'Keto Friendly' },
  { href: 'immuno-supportive', name: 'Immuno Supportive' },
  { href: 'gluten-free', name: 'Gluten Free' },
  { href: 'fodmap-free', name: 'FODMAP Free' },
  { href: 'fish-free', name: 'Fish Free' },
  { href: 'egg-free', name: 'Egg Free' },
  { href: 'DASH', name: 'DASH' },
  { href: 'dairy-free', name: 'Dairy Free' },
  { href: 'crustacean-free', name: 'Crustacean Free' },
  { href: 'celery-free', name: 'Celery Free' },
  { href: 'alcohol-free', name: 'Alcohol Free' },
  { href: 'alcohol-cocktail', name: 'Alcohol Cocktail' },
];

export const TimeConstants = [
  {
    labelName: '< 5 minutes',
    type: 'radio',
    name: 'time',
    value: '5',
    ariaLabel: '5 or less minutes',
  },
  {
    labelName: '5 - 10 minutes',
    type: 'radio',
    name: 'time',
    value: '5-10',
    ariaLabel: '5 to 10 minutes',
  },
  {
    labelName: '10 - 20 minutes',
    type: 'radio',
    name: 'time',
    value: '10-20',
    ariaLabel: '10 to 20 minutes',
  },
  {
    labelName: '20 - 30 minutes',
    type: 'radio',
    name: 'time',
    value: '20-30',
    ariaLabel: '20 to 30 minutes',
  },
  {
    labelName: '30 - 40 minutes',
    type: 'radio',
    name: 'time',
    value: '30-40',
    ariaLabel: '30 to 40 minutes',
  },
  {
    labelName: '40 - 50 minutes',
    type: 'radio',
    name: 'time',
    value: '40-50',
    ariaLabel: '40 to 50 minutes',
  },
  {
    labelName: '50 - 60minutes',
    type: 'radio',
    name: 'time',
    value: '50-60',
    ariaLabel: '50 to 60 minutes',
  },
  {
    labelName: '> 1 hours',
    type: 'radio',
    name: 'time',
    value: '60+',
    ariaLabel: '1 or more hours',
  },
];

export const IngredientsConstants = [
  {
    labelName: '< 5 ingredients',
    type: 'radio',
    name: 'ingr',
    value: '5',
    ariaLabel: '5 or less ingredients',
  },
  {
    labelName: '5 - 10 ingredients',
    type: 'radio',
    name: 'ingr',
    value: '5-10',
    ariaLabel: '5 to 10 ingredients',
  },
  {
    labelName: '10 - 20 ingredients',
    type: 'radio',
    name: 'ingr',
    value: '10-20',
    ariaLabel: '10 to 20 ingredients',
  },
  {
    labelName: '20 - 30 ingredients',
    type: 'radio',
    name: 'ingr',
    value: '20-30',
    ariaLabel: '20 to 30 ingredients',
  },
  { 
    labelName: '< 30 ingredients',
    type: 'radio',
    name: 'ingr',
    value: '30+',
    ariaLabel: '30 or more ingredients',
  },
];

export const CaloriesConstants = [
  {
    labelName: '< 50 calories',
    type: 'radio',
    name: 'calories',
    value: '< 50',
    ariaLabel: '50 or less calories',
  },
  {
    labelName: '50 - 100 calories',
    type: 'radio',
    name: 'calories',
    value: '50-100',
    ariaLabel: '50 to 100 calories',
  },
  {
    labelName: '100 - 200 calories',
    type: 'radio',
    name: 'calories',
    value: '100-200',
    ariaLabel: '100 to 200 calories',
  },
  {
    labelName: '200 - 300 calories',
    type: 'radio',
    name: 'calories',
    value: '200-300',
    ariaLabel: '200 to 300 calories',
  },
  {
    labelName: '300 - 400 calories',
    type: 'radio',
    name: 'calories',
    value: '300-400',
    ariaLabel: '300 to 400 calories',
  },
  {
    labelName: '400 - 500 calories',
    type: 'radio',
    name: 'calories',
    value: '400-500',
    ariaLabel: '400 to 500 calories',
  },
  {
    labelName: '> 500 calories',
    type: 'radio',
    name: 'calories',
    value: '500+',
    ariaLabel: '500 or more calories',
  },
];
export const DietConstants = [
  {
    labelName: 'Balanced',
    type: 'checkbox',
    name: 'dietType',
    value: 'balanced',
    ariaLabel: 'Balanced Diet',
  },
  {
    labelName: 'High Fiber',
    type: 'checkbox',
    name: 'dietType',
    value: 'high-fiber',
    ariaLabel: 'High Fiber Diet',
  },
  {
    labelName: 'High Protein',
    type: 'checkbox',
    name: 'dietType',
    value: 'high-protein',
    ariaLabel: 'High Protein Diet',
  },
  {
    labelName: 'Low Carb',
    type: 'checkbox',
    name: 'dietType',
    value: 'low-carb',
    ariaLabel: 'Low Carb Diet',
  },
  {
    labelName: 'Low Fat',
    type: 'checkbox',
    name: 'dietType',
    value: 'low-fat',
    ariaLabel: 'Low Fat Diet',
  },
  {
    labelName: 'Low Sodium',
    type: 'checkbox',
    name: 'dietType',
    value: 'low-sodium',
    ariaLabel: 'Low Sodium Diet',
  },
];

export const HealthConstants = [
  {
    labelName: 'Alcohol Cocktail',
    type: 'checkbox',
    name: 'health',
    value: 'alcohol-cocktail',
    ariaLabel: 'Alcohol Cocktail',
  },
  {
    labelName: 'Alcohol Free',
    type: 'checkbox',
    name: 'health',
    value: 'alcohol-free',
    ariaLabel: 'Alcohol-Free',
  },
  {
    labelName: 'Celery Free',
    type: 'checkbox',
    name: 'health',
    value: 'celery-free',
    ariaLabel: 'Celery-Free',
  },
  {
    labelName: 'Crustacean Free',
    type: 'checkbox',
    name: 'health',
    value: 'crustacean-free',
    ariaLabel: 'Crustacean-Free',
  },
  {
    labelName: 'Dairy Free',
    type: 'checkbox',
    name: 'health',
    value: 'dairy-free',
    ariaLabel: 'Dairy-Free',
  },
  {
    labelName: 'DASH',
    type: 'checkbox',
    name: 'health',
    value: 'DASH',
    ariaLabel: 'DASH Diet',
  },
  {
    labelName: 'Egg Free',
    type: 'checkbox',
    name: 'health',
    value: 'egg-free',
    ariaLabel: 'Egg-Free',
  },
  {
    labelName: 'Fish Free',
    type: 'checkbox',
    name: 'health',
    value: 'fish-free',
    ariaLabel: 'Fish-Free',
  },
  {
    labelName: 'FODMAP Free',
    type: 'checkbox',
    name: 'health',
    value: 'FODMAP-free',
    ariaLabel: 'FODMAP-Free',
  },
  {
    labelName: 'Gluten Free',
    type: 'checkbox',
    name: 'health',
    value: 'gluten-free',
    ariaLabel: 'Gluten-Free',
  },
  {
    labelName: 'Immuno Supportive',
    type: 'checkbox',
    name: 'health',
    value: 'immuno-supportive',
    ariaLabel: 'Immuno Supportive',
  },
  {
    labelName: 'Keto Friendly',
    type: 'checkbox',
    name: 'health',
    value: 'keto-friendly',
    ariaLabel: 'Keto Friendly',
  },
  {
    labelName: 'Kidney Friendly',
    type: 'checkbox',
    name: 'health',
    value: 'kidney-friendly',
    ariaLabel: 'Kidney Friendly',
  },
  {
    labelName: 'Kosher',
    type: 'checkbox',
    name: 'health',
    value: 'kosher',
    ariaLabel: 'Kosher',
  },
  {
    labelName: 'Low Fat Abs',
    type: 'checkbox',
    name: 'health',
    value: 'low-fat-abs',
    ariaLabel: 'Low Fat Abs',
  },
  {
    labelName: 'Low Potassium',
    type: 'checkbox',
    name: 'health',
    value: 'low-potassium',
    ariaLabel: 'Low Potassium',
  },
  {
    labelName: 'Low Sugar',
    type: 'checkbox',
    name: 'health',
    value: 'low-sugar',
    ariaLabel: 'Low Sugar',
  },
  {
    labelName: 'Lupine Free',
    type: 'checkbox',
    name: 'health',
    value: 'lupine-free',
    ariaLabel: 'Lupine-Free',
  },
  {
    labelName: 'Mediterranean Diet',
    type: 'checkbox',
    name: 'health',
    value: 'Mediterranean',
    ariaLabel: 'Mediterranean Diet',
  },
  {
    labelName: 'Mollusk Free',
    type: 'checkbox',
    name: 'health',
    value: 'mollusk-free',
    ariaLabel: 'Mollusk-Free',
  },
  {
    labelName: 'Mustard Free',
    type: 'checkbox',
    name: 'health',
    value: 'mustard-free',
    ariaLabel: 'Mustard-Free',
  },
  {
    labelName: 'No Oil Added',
    type: 'checkbox',
    name: 'health',
    value: 'no-oil-added',
    ariaLabel: 'No Oil Added',
  },
  {
    labelName: 'Paleo',
    type: 'checkbox',
    name: 'health',
    value: 'paleo',
    ariaLabel: 'Paleo',
  },
  {
    labelName: 'Peanut Free',
    type: 'checkbox',
    name: 'health',
    value: 'peanut-free',
    ariaLabel: 'Peanut-Free',
  },
  {
    labelName: 'Pescatarian',
    type: 'checkbox',
    name: 'health',
    value: 'pescatarian',
    ariaLabel: 'Pescatarian',
  },
  {
    labelName: 'Pork Free',
    type: 'checkbox',
    name: 'health',
    value: 'pork-free',
    ariaLabel: 'Pork-Free',
  },
  {
    labelName: 'Red Meat Free',
    type: 'checkbox',
    name: 'health',
    value: 'red-meat-free',
    ariaLabel: 'Red Meat-Free',
  },
  {
    labelName: 'Sesame Free',
    type: 'checkbox',
    name: 'health',
    value: 'sesame-free',
    ariaLabel: 'Sesame-Free',
  },
  {
    labelName: 'Shellfish Free',
    type: 'checkbox',
    name: 'health',
    value: 'shellfish-free',
    ariaLabel: 'Shellfish-Free',
  },
  {
    labelName: 'Soy Free',
    type: 'checkbox',
    name: 'health',
    value: 'soy-free',
    ariaLabel: 'Soy-Free',
  },
  {
    labelName: 'Sugar Conscious',
    type: 'checkbox',
    name: 'health',
    value: 'sugar-conscious',
    ariaLabel: 'Sugar Conscious',
  },
  {
    labelName: 'Sulfite Free',
    type: 'checkbox',
    name: 'health',
    value: 'sulfite-free',
    ariaLabel: 'Sulfite-Free',
  },
  {
    labelName: 'Tree Nut-Free',
    type: 'checkbox',
    name: 'health',
    value: 'tree-nut-free',
    ariaLabel: 'Tree Nut-Free',
  },
  {
    labelName: 'Vegan',
    type: 'checkbox',
    name: 'health',
    value: 'vegan',
    ariaLabel: 'Vegan',
  },
  {
    labelName: 'Vegetarian',
    type: 'checkbox',
    name: 'health',
    value: 'vegetarian',
    ariaLabel: 'Vegetarian',
  },
  {
    labelName: 'Wheat Free',
    type: 'checkbox',
    name: 'health',
    value: 'wheat-free',
    ariaLabel: 'Wheat-Free',
  },
];

export const MealConstants = [
  {
    labelName: 'Breakfast',
    type: 'checkbox',
    name: 'mealType',
    value: 'breakfast',
    ariaLabel: 'Breakfast',
  },
  {
    labelName: 'Dinner',
    type: 'checkbox',
    name: 'mealType',
    value: 'dinner',
    ariaLabel: 'Dinner',
  },
  {
    labelName: 'Lunch',
    type: 'checkbox',
    name: 'mealType',
    value: 'lunch',
    ariaLabel: 'Lunch',
  },
  {
    labelName: 'Snack',
    type: 'mealType',
    name: 'Snack',
    value: 'snack',
    ariaLabel: 'Snack',
  },
  {
    labelName: 'Teatime',
    type: 'checkbox',
    name: 'mealType',
    value: 'teatime',
    ariaLabel: 'Teatime',
  },
];

export const DishConstants = [
  {
    labelName: 'Biscuits and Cookies',
    type: 'checkbox',
    name: 'dishType',
    value: 'biscuits and cookies',
    ariaLabel: 'Biscuits and Cookies',
  },
  {
    labelName: 'Bread',
    type: 'checkbox',
    name: 'dishType',
    value: 'bread',
    ariaLabel: 'Bread',
  },
  {
    labelName: 'Cereals',
    type: 'checkbox',
    name: 'dishType',
    value: 'cereals',
    ariaLabel: 'Cereals',
  },
  {
    labelName: 'Condiments and Sauces',
    type: 'checkbox',
    name: 'dishType',
    value: 'condiments and sauces',
    ariaLabel: 'Condiments and Sauces',
  },
  {
    labelName: 'Desserts',
    type: 'checkbox',
    name: 'dishType',
    value: 'desserts',
    ariaLabel: 'Desserts',
  },
  {
    labelName: 'Drinks',
    type: 'checkbox',
    name: 'dishType',
    value: 'drinks',
    ariaLabel: 'Drinks',
  },
  {
    labelName: 'Main Course',
    type: 'checkbox',
    name: 'dishType',
    value: 'main course',
    ariaLabel: 'Main Course',
  },
  {
    labelName: 'Pancake',
    type: 'checkbox',
    name: 'dishType',
    value: 'pancake',
    ariaLabel: 'Pancake',
  },
  {
    labelName: 'Preps',
    type: 'checkbox',
    name: 'dishType',
    value: 'preps',
    ariaLabel: 'Preps',
  },
  {
    labelName: 'Preserve',
    type: 'checkbox',
    name: 'dishType',
    value: 'preserve',
    ariaLabel: 'Preserve',
  },
  {
    labelName: 'Salad',
    type: 'checkbox',
    name: 'dishType',
    value: 'salad',
    ariaLabel: 'Salad',
  },
  {
    labelName: 'Sandwiches',
    type: 'checkbox',
    name: 'dishType',
    value: 'sandwiches',
    ariaLabel: 'Sandwiches',
  },
  {
    labelName: 'Side Dish',
    type: 'checkbox',
    name: 'dishType',
    value: 'side dish',
    ariaLabel: 'Side Dish',
  },
  {
    labelName: 'Soup',
    type: 'checkbox',
    name: 'dishType',
    value: 'soup',
    ariaLabel: 'Soup',
  },
  {
    labelName: 'Starter',
    type: 'checkbox',
    name: 'dishType',
    value: 'starter',
    ariaLabel: 'Starter',
  },
  {
    labelName: 'Sweets',
    type: 'checkbox',
    name: 'dishType',
    value: 'sweets',
    ariaLabel: 'Sweets',
  },
];

export const CuisineConstants = [
  {
    labelName: 'American Cuisine',
    type: 'checkbox',
    name: 'cuisineType',
    value: 'american',
    ariaLabel: 'American Cuisine',
  },
  {
    labelName: 'Asian ',
    type: 'checkbox',
    name: 'cuisineType',
    value: 'asian',
    ariaLabel: 'Asian Cuisine',
  },
  {
    labelName: 'British',
    type: 'checkbox',
    name: 'cuisineType',
    value: 'british',
    ariaLabel: 'British Cuisine',
  },
  {
    labelName: 'Caribbean',
    type: 'checkbox',
    name: 'cuisineType',
    value: 'caribbean',
    ariaLabel: 'Caribbean Cuisine',
  },
  {
    labelName: 'Central European',
    type: 'checkbox',
    name: 'cuisineType',
    value: 'central europe',
    ariaLabel: 'Central European Cuisine',
  },
  {
    labelName: 'Chinese',
    type: 'checkbox',
    name: 'cuisineType',
    value: 'chinese',
    ariaLabel: 'Chinese Cuisine',
  },
  {
    labelName: 'Eastern European',
    type: 'checkbox',
    name: 'cuisineType',
    value: 'eastern europe',
    ariaLabel: 'Eastern European Cuisine',
  },
  {
    labelName: 'French',
    type: 'checkbox',
    name: 'cuisineType',
    value: 'french',
    ariaLabel: 'French Cuisine',
  },
  {
    labelName: 'Indian',
    type: 'checkbox',
    name: 'cuisineType',
    value: 'indian',
    ariaLabel: 'Indian Cuisine',
  },
  {
    labelName: 'Italian',
    type: 'checkbox',
    name: 'cuisineType',
    value: 'italian',
    ariaLabel: 'Italian Cuisine',
  },
  {
    labelName: 'Japanese',
    type: 'checkbox',
    name: 'cuisineType',
    value: 'japanese',
    ariaLabel: 'Japanese Cuisine',
  },
  {
    labelName: 'Kosher',
    type: 'checkbox',
    name: 'cuisineType',
    value: 'kosher',
    ariaLabel: 'Kosher Cuisine',
  },
  {
    labelName: 'Mediterranean',
    type: 'checkbox',
    name: 'cuisineType',
    value: 'mediterranean',
    ariaLabel: 'Mediterranean Cuisine',
  },
  {
    labelName: 'DASH',
    type: 'checkbox',
    name: 'cuisineType',
    value: 'mexican',
    ariaLabel: 'Mexican Cuisine',
  },
  {
    labelName: 'Middle Eastern',
    type: 'checkbox',
    name: 'cuisineType',
    value: 'middle eastern',
    ariaLabel: 'Middle Eastern Cuisine',
  },
  {
    labelName: 'Nordic',
    type: 'checkbox',
    name: 'cuisineType',
    value: 'nordic',
    ariaLabel: 'Nordic Cuisine',
  },
  {
    labelName: 'South American',
    type: 'checkbox',
    name: 'cuisineType',
    value: 'south american',
    ariaLabel: 'South American Cuisine',
  },
  {
    labelName: 'South East Asian',
    type: 'checkbox',
    name: 'cuisineType',
    value: 'south east asian',
    ariaLabel: 'South East Asian Cuisine',
  },
];
