export const tabs = [
  { id: 1, label: 'Breakfast' },
  { id: 2, label: 'Lunch' },
  { id: 3, label: 'Dinner' },
  { id: 4, label: 'Snack' },
  { id: 5, label: 'TeaTime' },
]

export const dietaryOptions = [
  { href: 'wheat-free', name: 'Wheat Free' },
  { href: 'vegetarian', name: 'Vegetarian' },
  { href: 'vegan', name: 'Vegan' },
  { href: 'tree-nut-free', name: 'Tree Nut Free' },
  { href: 'sulfite-free', name: 'Sulfite Free' },
  { href: 'sugar-conscious', name: 'Sugar Conscious' },
  { href: 'soy-free', name: 'Soy Free' },
  { href: 'shellfish-free', name: 'Shellfish Free' },
  { href: 'sesame-free', name: 'Sesame Free' },
  { href: 'red-meat-free', name: 'Red Meat Free' },
  { href: 'pork-free', name: 'Pork Free' },
  { href: 'pecatarian', name: 'Pescatarian' },
  { href: 'peanut-free', name: 'Peanut Free' },
  { href: 'paleo', name: 'Paleo' },
  { href: 'No-oil-added', name: 'No Oil Added' },
  { href: 'mustard-free', name: 'Mustard Free' },
  { href: 'mollusk-free', name: 'Mollusk Free' },
  { href: 'Mediterranean', name: 'Mediterranean' },
  { href: 'lupine-free', name: 'Lupine Free' },
  { href: 'low-sugar', name: 'Low Sugar' },
  { href: 'low-potassium', name: 'Low Potassium' },
  { href: 'kosher', name: 'Kosher' },
  { href: 'kidney-friendly', name: 'Kidney Friendly' },
  { href: 'keto-friendly', name: 'Keto Friendly' },
  { href: 'immuno-supportive', name: 'Immuno Supportive' },
  { href: 'gluten-free', name: 'Gluten Free' },
  { href: 'fodmap-free', name: 'FODMAP Free' },
  { href: 'fish-free', name: 'Fish Free' },
  { href: 'egg-free', name: 'Egg Free' },
  { href: 'DASH', name: 'DASH' },
  { href: 'dairy-free', name: 'Dairy Free' },
  { href: 'crustacean-free', name: 'Crustacean Free' },
  { href: 'celery-free', name: 'Celery Free' },
  { href: 'alcohol-free', name: 'Alcohol Free' },
  { href: 'alcohol-cocktail', name: 'Alcohol Cocktail' },
];

